Algoritmo "teste_condicional_Encadeamento_1"

Var
   hora:inteiro

Inicio
      escreva ("Digite uma hora do Dia :")
      leia (hora)
      
      se hora <12 então
         escreval (" Bom dia !")
      senão
           se (hora >=12) e (hora <18) então
              escreval ("Boa tarde!")
           senão
                escreval ("Boa noite !")
            fimse
           
      Fimse
      


Fimalgoritmo