Algoritmo "fatorial"
// Fazer um programa para ler um número natural N (valor máximo: 15),
// e depois calcular e mostrar o
// fatorial de N.
Var
   n,i,fatorial: inteiro



Inicio
      fatorial <-1  // elemento neutro de multiplicação


      escreva( " Digite o valor de N:")
      leia (n)

      para i de n ate 1 passo-1 faca
           fatorial<- fatorial* i



      fimpara

       escreval("FATORIAL =", FATORIAL )
Fimalgoritmo