 // Parametros:
// quantia: valor do salário bruto
// Efeito: retorna o imposto a ser pago
funcao imposto(quantia: real) : real


















Algoritmo "salario_liquido"
//Fazer um programa onde o usuário informa o valor bruto de um salário, e o
//programa informa qual o
//valor do salário líquido, já descontando impostos e previdência.
Var
   salario,salarioLiquido:real


Inicio
      escreval("Digite o valor do salario bruto:")
      leia (salario)


Fimalgoritmo